/**
 * 81 il, Türkçe alfabetik sırayla.
 *
 * Sıralama derleme zamanında sabit: `localeCompare('tr')` çalıştırılmıyor ki
 * liste her render'da yeniden sıralanmasın ve sunucu ile tarayıcı arasında
 * `Intl` farkından doğan bir tutarsızlık çıkmasın. Türkçe alfabede `ı` harfi
 * `i`den önce geldiği için Iğdır ve Isparta, İstanbul'dan önce duruyor.
 *
 * Sunucu tarafındaki doğrulama da bu listeyi kullanıyor (bkz. app/kayit/actions.ts):
 * forma elle gönderilen bir il adı listede yoksa başvuru kabul edilmiyor.
 *
 * İLÇE LİSTESİ BİLİNÇLİ OLARAK YOK. 970'i aşan ilçe adını elle taşımak, ilk
 * yazımda ve her idari değişiklikte hataya açık; formda ilçe bu yüzden serbest
 * metin alanı. İl bazlı ilçe listesi güvenilir bir kaynaktan (NVİ/TÜİK) alınıp
 * eklenirse alan `select`e çevrilir.
 */
export const iller = [
  'Adana',
  'Adıyaman',
  'Afyonkarahisar',
  'Ağrı',
  'Aksaray',
  'Amasya',
  'Ankara',
  'Antalya',
  'Ardahan',
  'Artvin',
  'Aydın',
  'Balıkesir',
  'Bartın',
  'Batman',
  'Bayburt',
  'Bilecik',
  'Bingöl',
  'Bitlis',
  'Bolu',
  'Burdur',
  'Bursa',
  'Çanakkale',
  'Çankırı',
  'Çorum',
  'Denizli',
  'Diyarbakır',
  'Düzce',
  'Edirne',
  'Elazığ',
  'Erzincan',
  'Erzurum',
  'Eskişehir',
  'Gaziantep',
  'Giresun',
  'Gümüşhane',
  'Hakkari',
  'Hatay',
  'Iğdır',
  'Isparta',
  'İstanbul',
  'İzmir',
  'Kahramanmaraş',
  'Karabük',
  'Karaman',
  'Kars',
  'Kastamonu',
  'Kayseri',
  'Kırıkkale',
  'Kırklareli',
  'Kırşehir',
  'Kilis',
  'Kocaeli',
  'Konya',
  'Kütahya',
  'Malatya',
  'Manisa',
  'Mardin',
  'Mersin',
  'Muğla',
  'Muş',
  'Nevşehir',
  'Niğde',
  'Ordu',
  'Osmaniye',
  'Rize',
  'Sakarya',
  'Samsun',
  'Siirt',
  'Sinop',
  'Sivas',
  'Şanlıurfa',
  'Şırnak',
  'Tekirdağ',
  'Tokat',
  'Trabzon',
  'Tunceli',
  'Uşak',
  'Van',
  'Yalova',
  'Yozgat',
  'Zonguldak',
] as const;
